//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacobHub {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JacobHub.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select 
        ///	ar_codart, 
        ///	ar_descr, 
        ///	bc_code, 
        ///	qta,
        ///	isnull((select lc_prezzo from listini where lc_codart = ar_codart and lc_listino = 2 and lc_conto = 0),0) as prezzo,
        ///  isnull((select  so_scont1 from sconti where so_codart = ar_codart and so_conto = 0 and so_clscan = 2),0) as sconto1,
        ///  isnull((select  so_scont2 from sconti where so_codart = ar_codart and so_conto = 0 and so_clscan = 2),0) as sconto2
        ///from artico 
        ///	inner join barcode on ar_codart = bc_codart 
        ///	inner join hhTmpCsv on barcode = bc_c [stringa troncata]&quot;;.
        /// </summary>
        internal static string ArticolidaFile {
            get {
                return ResourceManager.GetString("ArticolidaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select mm_codart, 
        ///mm_descr, 
        ///mm_quant,
        ///(select top 1 bc_code from barcode where bc_codart = mm_codart ) as Barcode, 
        ///isnull((select lc_prezzo from listini where lc_codart = mm_codart and lc_listino = 2),0) as prezzo,
        ///isnull((select so_scont1 from sconti where so_codart = mm_codart and so_clscan = 2),0)  as sc1,
        ///isnull((select so_scont2 from sconti where so_codart = mm_codart and so_clscan = 2),0)  as sc2,
        ///0 et1,
        ///0 et2,
        ///0 et3
        ///from movmag
        ///where mm_tipork = &apos;B&apos; and concat( mm_numdoc, &apos;/&apos;, mm_serie, [stringa troncata]&quot;;.
        /// </summary>
        internal static string ArticoliFromMovmag {
            get {
                return ResourceManager.GetString("ArticoliFromMovmag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select mm_codart, 
        ///mm_descr, 
        ///mm_quant,
        ///(select top 1 bc_code from barcode where bc_codart = mm_codart ) as Barcode, 
        ///isnull((select lc_prezzo from listini where lc_codart = mm_codart and lc_listino = 2),0) as prezzo,
        ///isnull((select so_scont1 from sconti where so_codart = mm_codart and so_clscan = 2),0)  as sc1,
        ///isnull((select so_scont2 from sconti where so_codart = mm_codart and so_clscan = 2),0)  as sc2,
        ///0 et1,
        ///0 et2,
        ///0 et3
        ///from movmag
        ///inner join testmag on tm_numdoc = mm_numdoc and tm_serie =  [stringa troncata]&quot;;.
        /// </summary>
        internal static string Articolifrommovmagfatt {
            get {
                return ResourceManager.GetString("Articolifrommovmagfatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///select * from V_Artico order by ar_codart
        ///
        ///.
        /// </summary>
        internal static string articoligriglia {
            get {
                return ResourceManager.GetString("articoligriglia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select * from hhetichette where id &gt; 3.
        /// </summary>
        internal static string et {
            get {
                return ResourceManager.GetString("et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select ar_codart, ar_descr from artico order by ar_codart asc.
        /// </summary>
        internal static string getArticoli {
            get {
                return ResourceManager.GetString("getArticoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select concat( tm_numdoc, &apos;/&apos;, tm_serie, &apos;/&apos;, tm_anno) as Chiave from testmag where tm_tipork = &apos;B&apos; and tm_serie = @serie
        ///
        ///
        ///.
        /// </summary>
        internal static string Getddt {
            get {
                return ResourceManager.GetString("Getddt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select concat( tm_numdoc, &apos;/&apos;, tm_serie, &apos;/&apos;, tm_anno) as Chiave from testmag where tm_tipork = &apos;B&apos; and tm_serie = @serie.
        /// </summary>
        internal static string GetFatture {
            get {
                return ResourceManager.GetString("GetFatture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select * from hhTMP_ETARTICO .
        /// </summary>
        internal static string getTmpArtico {
            get {
                return ResourceManager.GetString("getTmpArtico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select op_id, op_name from hhoperatori.
        /// </summary>
        internal static string Operatori {
            get {
                return ResourceManager.GetString("Operatori", resourceCulture);
            }
        }
    }
}
